---
deployment:
	tasks:
		- export DEPLOYPATH=/home/charlesd/public_html/
		- /cp /home/charlesd/repositories/Ticket-project/Add-category.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/Add-ticket.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/README.md $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/accesstoken.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/add-category.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/add-category.contr.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/add-category.inc.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/buy_ticket.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/buy_ticket.contr.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/buy_ticket.inc.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/buy_ticket.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/call-back.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/composer.json $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/composer.lock $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/contact.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/cpanel-automation-script.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/create-new-password.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/dashboard-style.css $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/dashboard.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/dbh.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/events-and-tickets.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/footer-style.css $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/footer.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/footerpage.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/forgot-password.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/header.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/home.php $DEPLOYPATH
		- /cp -R /home/charlesd/repositories/Ticket-project/images $DEPLOYPATH
		- /cp -R /home/charlesd/repositories/Ticket-project/includes $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/index.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/log_user_activity.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/login.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/logout.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/main.js $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/map.php $DEPLOYPATH
		- /cp -R /home/charlesd/repositories/Ticket-project/myticket.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/registration.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/report.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/reset-password.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/script.js $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/stk.json $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/stkpush.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/style.css $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/style1.css $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/style2.css $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket-delete.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket-inc.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket-post.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket-status.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket-update.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket.contr.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/ticket_pricing.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-add.classes.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-add.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-delete.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-operation.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-update.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-update.contr.class.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/user-update.php $DEPLOYPATH
		- /cp /home/charlesd/repositories/Ticket-project/users.php $DEPLOYPATH
		- /cp -R /home/charlesd/repositories/Ticket-project/vendor $DEPLOYPATH
